### ISSUE TITLE
Update class diagram

### ISSUE THREAD

**Issue by waltertan98** [nobodomon/ICT2106_P3-1#25]

**Comment by waltertan98** [comment]
Things to be added into class diagram

- boundary class

**Comment by waltertan98** [comment]
Things to check and take note of

- interfaces that would be used by other control
- arrow head and direction
- notation if there is an arrow head

**Comment by micdiary** [comment]
Discussed in 9/3 LAB:
identified Single Responsibility Principle in Class Diagram (volunteer & volunteerwork)
identified Strategy behavioral pattern (permission)

**Comment by micdiary** [comment]
identified singleton (database) & factory (different user accounts)

**Comment by waltertan98** [comment]
edited the class diagrams to the correct type interfaces -> boundary


![Image](https://user-images.githubusercontent.com/93696258/223956264-901ebf9a-d077-497c-a72c-d1a1cfa4db15.png)

**Comment by waltertan98** [comment]
Kenneth - Volunteer
Tennyson - Permission Managment
Joan - Expenses
Janice - Approval
Michael - Reports
Chun Guan - Employees

**Comment by joanlimjt** [comment]
Updated expense entity to apply single responsibility  principle




![Image](https://user-images.githubusercontent.com/94058396/225819334-6e8792b3-b395-4a8e-919c-e88141da80e1.png)

**Comment by joanlimjt** [comment]
For SOLID principles, we will be using single responsibility principle and interface segregation principle
For design pattern, we will be using singleton and template method

**Comment by waltertan98** [comment]
![Image](https://user-images.githubusercontent.com/93696258/225577985-38611488-ef55-45d5-9efe-94986d83ec26.png)

SOLID "I" principle added into the class diagram

**Comment by waltertan98** [comment]
![Image](https://user-images.githubusercontent.com/93696258/225578551-e4c5f072-6dfa-4fb7-8665-afa30809cf59.png)

template pattern shown in class diagram

**Comment by micdiary** [comment]
![Image](https://user-images.githubusercontent.com/39511153/226159712-ad4d7896-9de0-4b91-be8d-4f0d2c2a3202.png)



update minor changes to volunteerworkcontrol

**Comment by micdiary** [comment]
![Image](https://user-images.githubusercontent.com/39511153/226159891-cdbcd2c1-2a8f-4c6e-aa1c-f83750b10b7b.png)



![Image](https://user-images.githubusercontent.com/39511153/226159896-01c6d11c-7b05-4a87-a0da-f7d43bd7563a.png)

update report control, controller, repoOut

**Comment by micdiary** [comment]
![Image](https://user-images.githubusercontent.com/39511153/227531868-d38ba619-88fe-4f9d-80f5-b7c93074f6f9.png)

removed reportrepositoryin

**Comment by waltertan98** [comment]
class diagram shared with class for integration
