### ISSUE TITLE
Generate Employee Expenses Report

### ISSUE THREAD

**Issue by micdiary** [nobodomon/ICT2106_P3-1#29]

**Comment by nobodomon** [comment]
- [x] Create endpoints for calling on front end
- [x] Create data getter
- [ ] Front end for displaying report


![Image](https://user-images.githubusercontent.com/25370651/224274788-1f9195cf-8f45-4194-b20a-35565ba6458a.png)

**Comment by nobodomon** [comment]
Decided to scrap front end display of report.
